export const BOOKS_REQUEST = "BOOKS_REQUEST"
export const BOOKS_SUCCESS = "BOOKS_SUCCESS"
export const BOOKS_FAIL = "BOOKS_FAIL"


export const ALL_BOOKS_REQUEST = "ALL_BOOKS_REQUEST"
export const ALL_BOOKS_SUCCESS = "ALL_BOOKS_SUCCESS"
export const ALL_BOOKS_FAIL = "ALL_BOOKS_FAIL"

export const WISHLIST_REQUEST = "FAVORITE_REQUEST"
export const WISHLIST_SUCCESS = "FAVORITE_SUCCESS"
export const WISHLIST_FAIL = "FAVORITE_FAIL"

export const ADD_WISHLIST_REQUEST = "ADD_FAVORITE_REQUEST"
export const ADD_WISHLIST_SUCCESS = "ADD_FAVORITE_SUCCESS"
export const ADD_WISHLIST_FAIL = "ADD_FAVORITE_FAIL"

export const REMOVE_WISHLIST_REQUEST = "REMOVE_FAVORITE_REQUEST"
export const REMOVE_WISHLIST_SUCCESS = "REMOVE_FAVORITE_SUCCESS"
export const REMOVE_WISHLIST_FAIL = "REMOVE_FAVORITE_FAIL"



export const CLEAR_ERRORS   =  "CLEAR_ERRORS" 